# Generated by Django 5.1.6 on 2025-02-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='level',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Abreviatura'),
        ),
    ]
